package(default_visibility = ["//visibility:public"])

filegroup(
    name = 'simulator_srcs',
    srcs = [ 'codegen.cpp',
             'dag_optimiziation.cpp',
             'interpret.cpp',
             'layout.cpp',
             'low_rep.cpp',
             'multithreading.cpp',
             'output.cpp',
             'print_c.cpp',
             'sim.cpp',
             'subcircuit.cpp' ])

filegroup(
    name = 'simulator_hdrs',
    srcs = [ 'bsim_lib.hpp',
             'codegen.h',
             'coreirsim.h',
             'dag_optimization.h',
             'interpreter.h',
             'layout.h',
             'low_rep.h',
             'multithreading.h',
             'output.h',
             'print_c.h',
             'simulator.h',
             'subcircuit.h' ])
