# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dillon/CppWorkspace/coreir

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dillon/CppWorkspace/coreir

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dillon/CppWorkspace/coreir/CMakeFiles /Users/dillon/CppWorkspace/coreir/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dillon/CppWorkspace/coreir/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named coreir-simulator

# Build rule for target.
coreir-simulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir-simulator
.PHONY : coreir-simulator

# fast build rule for target.
coreir-simulator/fast:
	$(MAKE) -f src/CMakeFiles/coreir-simulator.dir/build.make src/CMakeFiles/coreir-simulator.dir/build
.PHONY : coreir-simulator/fast

#=============================================================================
# Target rules for targets named coreir-bin

# Build rule for target.
coreir-bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir-bin
.PHONY : coreir-bin

# fast build rule for target.
coreir-bin/fast:
	$(MAKE) -f src/CMakeFiles/coreir-bin.dir/build.make src/CMakeFiles/coreir-bin.dir/build
.PHONY : coreir-bin/fast

#=============================================================================
# Target rules for targets named coreir-interpreter

# Build rule for target.
coreir-interpreter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir-interpreter
.PHONY : coreir-interpreter

# fast build rule for target.
coreir-interpreter/fast:
	$(MAKE) -f src/CMakeFiles/coreir-interpreter.dir/build.make src/CMakeFiles/coreir-interpreter.dir/build
.PHONY : coreir-interpreter/fast

#=============================================================================
# Target rules for targets named coreir

# Build rule for target.
coreir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir
.PHONY : coreir

# fast build rule for target.
coreir/fast:
	$(MAKE) -f src/CMakeFiles/coreir.dir/build.make src/CMakeFiles/coreir.dir/build
.PHONY : coreir/fast

#=============================================================================
# Target rules for targets named coreir-aetherlinglib

# Build rule for target.
coreir-aetherlinglib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir-aetherlinglib
.PHONY : coreir-aetherlinglib

# fast build rule for target.
coreir-aetherlinglib/fast:
	$(MAKE) -f src/libs/CMakeFiles/coreir-aetherlinglib.dir/build.make src/libs/CMakeFiles/coreir-aetherlinglib.dir/build
.PHONY : coreir-aetherlinglib/fast

#=============================================================================
# Target rules for targets named coreir-ice40

# Build rule for target.
coreir-ice40: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir-ice40
.PHONY : coreir-ice40

# fast build rule for target.
coreir-ice40/fast:
	$(MAKE) -f src/libs/CMakeFiles/coreir-ice40.dir/build.make src/libs/CMakeFiles/coreir-ice40.dir/build
.PHONY : coreir-ice40/fast

#=============================================================================
# Target rules for targets named coreir-float

# Build rule for target.
coreir-float: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir-float
.PHONY : coreir-float

# fast build rule for target.
coreir-float/fast:
	$(MAKE) -f src/libs/CMakeFiles/coreir-float.dir/build.make src/libs/CMakeFiles/coreir-float.dir/build
.PHONY : coreir-float/fast

#=============================================================================
# Target rules for targets named coreir-rtlil

# Build rule for target.
coreir-rtlil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir-rtlil
.PHONY : coreir-rtlil

# fast build rule for target.
coreir-rtlil/fast:
	$(MAKE) -f src/libs/CMakeFiles/coreir-rtlil.dir/build.make src/libs/CMakeFiles/coreir-rtlil.dir/build
.PHONY : coreir-rtlil/fast

#=============================================================================
# Target rules for targets named coreir-commonlib

# Build rule for target.
coreir-commonlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir-commonlib
.PHONY : coreir-commonlib

# fast build rule for target.
coreir-commonlib/fast:
	$(MAKE) -f src/libs/CMakeFiles/coreir-commonlib.dir/build.make src/libs/CMakeFiles/coreir-commonlib.dir/build
.PHONY : coreir-commonlib/fast

#=============================================================================
# Target rules for targets named coreirsim

# Build rule for target.
coreirsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreirsim
.PHONY : coreirsim

# fast build rule for target.
coreirsim/fast:
	$(MAKE) -f src/simulator/CMakeFiles/coreirsim.dir/build.make src/simulator/CMakeFiles/coreirsim.dir/build
.PHONY : coreirsim/fast

#=============================================================================
# Target rules for targets named coreirsim-c

# Build rule for target.
coreirsim-c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreirsim-c
.PHONY : coreirsim-c

# fast build rule for target.
coreirsim-c/fast:
	$(MAKE) -f src/coreir-c/CMakeFiles/coreirsim-c.dir/build.make src/coreir-c/CMakeFiles/coreirsim-c.dir/build
.PHONY : coreirsim-c/fast

#=============================================================================
# Target rules for targets named coreir-c

# Build rule for target.
coreir-c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreir-c
.PHONY : coreir-c

# fast build rule for target.
coreir-c/fast:
	$(MAKE) -f src/coreir-c/CMakeFiles/coreir-c.dir/build.make src/coreir-c/CMakeFiles/coreir-c.dir/build
.PHONY : coreir-c/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/strip"
	@echo "... uninstall"
	@echo "... coreir-simulator"
	@echo "... coreir-bin"
	@echo "... coreir-interpreter"
	@echo "... coreir"
	@echo "... coreir-aetherlinglib"
	@echo "... coreir-ice40"
	@echo "... coreir-float"
	@echo "... coreir-rtlil"
	@echo "... coreir-commonlib"
	@echo "... coreirsim"
	@echo "... coreirsim-c"
	@echo "... coreir-c"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

