#!/bin/sh
#cd unit; ./run -memcheck
set -e
cd unit; ./run; cd -
cd unit-c; ./run; cd -
cd ext; ./run; cd -
cd simulator; ./run; cd -
GREEN='\033[0;32m'
NC='\033[0m'
echo -e "${GREEN} PASSED ALL TESTS!${NC}"
