package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'headers_hdrs',
    hdrs = [ 'core.hpp',
             'corebit.hpp',
             'mantle.hpp',
             'memories.hpp' ])
