package(default_visibility = ["//visibility:public"])

filegroup(
    name = 'headers_hdrs',
    srcs = [ 'core.hpp',
             'corebit.hpp',
             'mantle.hpp',
             'memories.hpp' ])
