package(default_visibility = ["//visibility:public"])

filegroup(
    name = 'definitions_hdrs',
    srcs = [ 'coreFirrtl.hpp',
             'coreVerilog.hpp',
             'corebitFirrtl.hpp',
             'corebitVerilog.hpp' ])
