package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'definitions',
    hdrs = [ 'coreFirrtl.hpp',
             'coreVerilog.hpp',
             'corebitFirrtl.hpp',
             'corebitVerilog.hpp' ])
