package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'passes',
    hdrs = [ 'common.h' ],
    deps = [ '//passes/analysis:analysis_hdrs',
             '//passes/transform:transform_hdrs' ])
