package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'passes',
    deps = [ ':passes_hdrs',
             '//passes/analysis:analysis_hdrs',
             '//passes/transform:transform_hdrs' ])

cc_library(
    name = 'passes_hdrs',
    hdrs = [ 'common.h' ])
