

all:
	make -C coreir-c
	make -C passes
	make -C libs

so:
	make -C coreir-c so
	make -C passes so
	make -C libs so

dylib:
	make -C coreir-c dylib
	make -C passes dylib
	make -C libs dylib


clean:
	make -C coreir-c clean
	make -C passes clean
	make -C libs clean
