#include "coreir/passes/transform/rename_yosys_auto_generated_instances.h"

#include "coreir.h"

using namespace std;
using namespace CoreIR;


//Do not forget to set this static variable!!
string Passes::RenameYosysAutoGeneratedInstances::ID = "rename_yosys_auto_generated_instances";
bool Passes::RenameYosysAutoGeneratedInstances::runOnModule(Module* m) {
  assert(false);
  return false;
}
