package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'common',
    srcs = [ 'logging_lite.cpp' ],
    deps = [ ':common_hdrs' ] )

cc_library(
    name = 'common_hdrs',
    hdrs = [ 'algorithm.h',
             'common-macros.h',
             'cxxopts.h',
             'defer.hpp',
             'logging_lite.hpp' ])
