package(default_visibility = ["//visibility:public"])

filegroup(
    name = 'common_srcs',
    srcs = [ 'logging_lite.cpp' ])

filegroup(
    name = 'common_hdrs',
    srcs = [ 'algorithm.h',
             'common-macros.h',
             'cxxopts.h',
             'defer.hpp',
             'logging_lite.hpp' ])
