cc_library(
    name = 'common',
    hdrs = [ 'algorithm.h',
             'common-macros.h',
             'cxxopts.h',
             'defer.hpp',
             'logging_lite.hpp' ],
    srcs = [ 'logging_lite.cpp' ])
