package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'utils_hdrs',
    hdrs = [ 'op_graph.h',
             'primitive.h',
             'util.h',
             'utils.h',
             'wire_node.h',
             'wiring_utils.h' ])
