package(default_visibility = ["//visibility:public"])

filegroup(
    name = 'utils_hdrs',
    srcs = [ 'op_graph.h',
             'primitive.h',
             'util.h',
             'utils.h',
             'wire_node.h',
             'wiring_utils.h' ])
