package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'coreir-c',
    srcs = [ 'coreir-c.cpp',
             'simulator-c.cpp',
             'types-c.cpp',
             'values-c.cpp' ])

cc_library(
    name = 'coreir-c_hdrs',
    hdrs = [ 'common-c.hpp',
             'coreir-simulator.h',
             'coreir-types.h',
             'coreir-values.h',
             'coreir.h',
             'ctypes.h' ])
