package(default_visibility = ["//visibility:public"])

filegroup(
    name = 'coreir-c_srcs',
    srcs = [ 'coreir-c.cpp',
             'simulator-c.cpp',
             'types-c.cpp',
             'values-c.cpp' ])

filegroup(
    name = 'coreir-c_hdrs',
    srcs = [ 'common-c.hpp',
             'coreir-simulator.h',
             'coreir-types.h',
             'coreir-values.h',
             'coreir.h',
             'ctypes.h' ])
