#ifndef COREIR_RENAME_YOSYS_AUTO_GENERATED_INSTANCES_HPP_
#define COREIR_RENAME_YOSYS_AUTO_GENERATED_INSTANCES_HPP_

#include "coreir.h"

//Define the analysis passes in CoreIR::Passes
namespace CoreIR {
namespace Passes {

//This will add directed connection metadata to modules
class RenameYosysAutoGeneratedInstances : public ModulePass {
  
  public:
    static std::string ID;
    RenameYosysAutoGeneratedInstances() : ModulePass(ID, "Give simpler names to instances that have been automatically generated by yosys") {}
    bool runOnModule(Module* m) override;
};

}
}

#endif
