#ifndef COREIR_RENAME_YOSYS_AUTO_GENERATED_INSTANCES_HPP_
#define COREIR_RENAME_YOSYS_AUTO_GENERATED_INSTANCES_HPP_

#include "coreir.h"

// Define the analysis passes in CoreIR::Passes
namespace CoreIR {
namespace Passes {

// This will add directed connection metadata to modules
class RenameYosysAutoGeneratedInstances : public ModulePass {

 public:
  RenameYosysAutoGeneratedInstances()
      : ModulePass(
          "rename_yosys_auto_generated_instances",
          "Give simpler names to instances that have been automatically "
          "generated by yosys") {}
  bool runOnModule(Module* m) override;
};

}  // namespace Passes
}  // namespace CoreIR

#endif
