package(default_visibility = ["//visibility:public"])

cc_library(
    name = 'aetherlinglib',
    hdrs = [ 'aeDehydrate.h',
             'aeFlatten.h',
             'aeMap.h',
             'aeOverlapPartition.h',
             'aeReduce.h',
             'aeStreamifyArrayify.h',
             'aeZip2.h' ])
